version: 2
jobs:
  build:
    machine: true
    steps:
    
      - checkout
                  
      - run:
          name: Build and run problems
          command: make build run
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
